Send Form screen btn added
DaniilMurzin/SellArt pull request #6
Opened 2023-04-25 10:44 UTC by DaniilMurzin

2023-04-25 11:33 UTC, borisverbitckii requested changes

2023-04-25 11:33 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Splash/SplashViewController.swift
> +        btn.translatesAutoresizingMaskIntoConstraints = false
Надо перенести в инициализатор самой кнопки

2023-04-25 11:33 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Splash/SplashViewController.swift
> +            button.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 32),
Все переменные надо переносить вниз в
 private enum LocalConstants {
     static let leftInset: CGFloat = 32
}

2023-04-25 11:33 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/ButtonView.swift
> +        let attributedTitle = Strings.buttonTitle.toStyledForButtonAttributedString()
Нужно доперевести в локализации нормальный текст для кнопок, а также текст должен устанавливаться либо за пределами кнопки публичным методом, либо у кнопки должны быть разные состояния, исходя из которых они настраиваются

Например, можно сделать authButton, который будет иметь 2 состояния 
enum AuthButtonState {
    case auth, registration
}

Исходя из этого настраивать уже текста и внешний вид

2023-04-25 11:33 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/ButtonView.swift
> +        button.addTarget(self, action: #selector(buttonTapped), for: .touchUpInside)
Надо вообще у всех методов писать с новой строки переменные, потому что когда они в ряд - читать невозможно

2023-04-25 11:33 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/ButtonView.swift
> +class ButtonView: UIView {
Чтобы сделать свою кнопку, надо наследоваться от UIButton

2023-04-25 11:33 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/ButtonView.swift
> +    private func setupConstraints() {
Эти констрейнты будут не нужны, когда наследуешься от UIButton

2023-04-25 11:33 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/ButtonView.swift
> +    @objc private func buttonTapped() {
Действие должно настраиваться за пределами кнопки

2023-04-26 08:29 UTC, borisverbitckii requested changes

2023-04-26 08:29 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Splash/SplashViewController.swift
> +    private lazy var button = ButtonView(state: .submitForm )
Lazy переменные надо помечать тогда, когда надо обратиться к self, в противном случае можно просто private let

2023-04-26 08:29 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Splash/SplashViewController.swift
>      private enum LocalConstants {
Лучше поместить за пределы класса или в самый верх или в самый низ, я обычно в самый низ

2023-04-26 08:29 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Splash/SplashViewController.swift
>  extension SplashViewController: SplashViewProtocol {
Там в этом расширении setButtonTitle метод, он не нужен, потому что мы можем напрямую применять текст в класс нашей кнопки

2023-04-27 15:45 UTC, DaniilMurzin commented on SellArt/Source/Presentation/Modules/Splash/SplashViewController.swift
>      private enum LocalConstants {
ты ведь про enum?)

2023-04-28 07:56 UTC, merged