CollectionView + CustomCell
DaniilMurzin/SellArt pull request #9
Opened 2023-05-03 15:34 UTC by DaniilMurzin

2023-05-04 05:16 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +    lazy var collectionViewLayout: UICollectionViewFlowLayout = {
FlowLayout можно создать внутри 
lazy var collectionView: UICollectionView 
и там же по месту настроить

2023-05-04 05:17 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +
Зачем столько пробелов между кодом?

2023-05-04 05:18 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +                              UICollectionViewDelegateFlowLayout {
Обычно делают одно расширение - один протокол

2023-05-04 05:19 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +        collectionView.backgroundColor = .mainBackgroundColor
Это внутрь настройки коллекции

2023-05-04 05:21 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +            print("Downcast error")
Лучше, если ты хочешь узнать, что что-то пошло не так, то вставлять assertionFailure. В таком случае приложение будет падать в дебаг режиме, но в релизе падения не будет

2023-05-04 05:23 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +            paintingCell.setPaintingImage(paintings[indexPath.item])
Лучше сразу для ячейки подготовить модель с картиной, ее id, ценой и тд, всем тем, что надо, чтобы отобразить информацию этой ячейки. И должен быть массив не просто картин, а именно таких моделей, сгенерировать их можно в chatGPT. Размещать лучше сразу в презентере, потому что там они и будут размещаться, когда мы их загрузим удаленно

2023-05-04 05:23 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +            print("Downcast error")
Вообще, как по мне, классически тут пишут guard let и это сильно привычнее

2023-05-04 06:36 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +//func collectionView(
Это разве нужно?

2023-05-04 06:37 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +    lazy var collectionView: UICollectionView = {
Публично, потому что где то из вне используется? Если нет, то надо сделать все приватным, что можно

2023-05-04 06:38 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +        label.text = "1 000 000 $"
Сделать метод setupCell, принимать в этот метод модель и подкидывать значения для всех вьюх в этом методе

2023-05-04 06:38 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    private let  ArtistArtPriceStackView: UIStackView = {
с маленькой буквы

2023-05-04 06:38 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +        view.axis  = NSLayoutConstraint.Axis.vertical
Можно просто .vertical

2023-05-04 06:41 UTC, borisverbitckii requested changes

2023-05-04 06:41 UTC, borisverbitckii commented on SellArt.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
пустий коммент, чтобы можно было поменять статус пра

2023-05-09 04:12 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Model/Paintings.swift
> +class PaintingsModel {
Все модели надо хранить в презентере, потому что когда ты будешь их с сети качать, они там и окажутся. Надо сразу туда их складывать, чтобы сразу продумывать все связи и то, какие данные куда надо передавать

2023-05-09 04:12 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Model/Paintings.swift
> +class PaintingsModel {
Плюс модель должна быть структурой. Структуры мы будем хранить в  feature слое, когда будем делать фичи.

2023-05-09 04:13 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +    var presenter: MainPresenterProtocol
А зачем презентер публичный?

2023-05-09 04:14 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +        $0.setCollectionViewLayout(layout, animated: false)
Проще было тут же инициализировать коллекцию и при инициализации в нее подкинуть FlowLayout

2023-05-09 04:17 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +        presenter.loadPaintings()
Тебе надо добавить в loadPaintings completion: @escaping ([Paintings]) -> Void и по приходу информации обновлять тут UI. updatePaintings не нужен

2023-05-09 04:19 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
Рекомендуется контролировать ширину кода от 80 до 120 символов. Так читать удобнее. В xcode  можно включить, чтобы была вертикальная линия, которая показывала бы выходишь ты за пределы или нет. Перенос на новые строки решил бы этот вопрос

2023-05-09 04:20 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    private lazy var favoriteButton = UserActionsButtons(type: .favorite)
Нет необходимости делать lazy, потому что тебе не надо обращаться в self. Можно просто оставить  private let
Аналогично для кода ниже

2023-05-09 04:21 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +            format: "%.2f $",
Все вот эти приготовления информации должны делаться в презентере. Потому что тогда всегда будет понятно, что любая логика - это презентере и не придется искать что-то по проекту

2023-05-09 04:22 UTC, borisverbitckii commented on SellArt/Source/Infrastructure/Extensions/UIcolor + Hex.swift
> +// убрать
Нигде не используется, так что лучше сразу убрать

2023-05-09 07:10 UTC, borisverbitckii requested changes

2023-05-09 07:10 UTC, borisverbitckii commented on SellArt.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
пустой комментарий

2023-10-01 12:46 UTC, DaniilMurzin commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +    var presenter: MainPresenterProtocol
он же в билдере используется

2023-10-01 16:30 UTC, DaniilMurzin commented on SellArt/Source/Presentation/Modules/Model/Paintings.swift
> +class PaintingsModel {
Когда ты говоришь о том, что все модели следует хранить в презентере, ты имеешь в виду, что презентер должен контролировать загрузку и обработку данных, но не обязательно содержать сами модели внутри себя? добавлять их прямо в класс презентара? 
Ииии еще feature слой  где следует хранить структуры. Подробнее можешь об этом рассказать?  Где именно этот слой должен располагаться в структуре проекта?

2023-10-01 16:35 UTC, DaniilMurzin commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +            format: "%.2f $",
func loadPaintings(completion: @escaping ([FormattedPainting]) -> Void)  функцию  переделать чтобы она форматировала цену ??

2023-10-04 13:39 UTC, borisverbitckii requested changes

2023-10-04 13:39 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +            format: "%.2f $",
Я не понял, про какую ты функцию говоришь, но подготовка строки (формат и вот это все) - надо в презентер переноситься потому что там у нас вся бизнес логика.

2023-10-04 13:39 UTC, borisverbitckii commented on SellArt.xcodeproj/project.pbxproj
> +		B612F1DC29FFEE2F006041CF /* PaintingCollectionViewCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = B612F1DB29FFEE2F006041CF /* PaintingCollectionViewCell.swift */; };
Этот коммент для того, чтобы начать ревью и я мог оставлять комменты в Xcode напрямую

2023-10-04 13:39 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/TempFeature/Paintings.swift
> +struct PaintingsModel {
Создай наравне с папками infrastructure и presentation папку features и там создай папку MainScreenContentFeature, а в ней файл PaintingsRepository. Почитай, что за паттерн такой репозиторий, и зачем это надо. Потом расскажешь, а я если что поправлю

2023-10-11 04:45 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    static let identifier = "PaintingCollectionViewCell"
static let identifier = String(describing: self)
Можно так и сделать это расширением UICollectionViewCell

2023-10-11 04:46 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    private let  artistArtPriceStackView: UIStackView = {
SwiftLint должен был подсветить, что лишний пробел. Если он не работает, глянь, мог сломаться почему-то

2023-10-11 04:46 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    private let  artistArtPriceStackView: UIStackView = {
Можно сделать lazy var и сюда сразу добавить все arrangedSubview по месту

2023-10-11 04:50 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    func setupCell(with painting: Paintings, formattedPrice: String) {
С новых строк параметры в функциях. 

А еще можно так
func setupCell(
    with painting: Paintings,
    formattedPrice: String
)

Так в android делают, выглядит тоже ничего, в обоих случаях читать приятнее

2023-10-11 04:51 UTC, borisverbitckii commented on SellArt/Source/Infrastructure/Application/SceneDelegate.swift
> +        let tabBarController = MainModuleBuilder.build()
Вынеси tabBarController  отдельно от MainModule. Потому что у тебя в таббаре потом будет несколько экранов внутри него, и один из них - это Main, который был до таббарконтроллера

2023-10-11 04:52 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainModuleBilder.swift
> +        mainViewController.tabBarItem.title = "Gallery"
Вынеси в строки и локализации

2023-10-11 04:55 UTC, borisverbitckii commented on SellArt/Source/Presentation/Modules/Main/MainViewController.swift
> +        // Added extra height for buttons and labels
Надо бы наверное определиться, что будем делать с комментариями. Либо везде на английском, либо везде на русском.
Да и в целом как-будто этот комментарий и не нужен

2023-10-11 04:55 UTC, borisverbitckii commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    static let identifier = "PaintingCollectionViewCell"
И перенести в core

2023-10-14 14:12 UTC, DaniilMurzin commented on SellArt/Source/Presentation/Views/Cells/PaintingCollectionViewCell.swift
> +    static let identifier = "PaintingCollectionViewCell"
extension UICollectionViewCell {
    static var identifier: String {
        return String(describing: self)
    }
}
делаю такое расширение и создаю отдельный файл с расширением?

2023-10-16 06:31 UTC, borisverbitckii approved these changes

2023-10-16 09:03 UTC, merged